library(knitr)
library(rvest)
library(gsubfn)
library(tidyr)
library(shiny)
library(httr)
library(reshape2)
library(dygraphs)
library(xts)
library(tidyverse)
library(lubridate)
library(tmap)
library(plotrix)
library(rmarkdown)
library(DT)
library(rgdal)
library(rgeos)
library(digest)
library(readr)
library(rvest)
library(dplyr)
library(gsubfn)
library(ggplot2)
library(mosaic)
library(maptools)
library(extrafont)
library(tmap)
library(factoextra)
library(ggrepel)

options(gsubfn.engine="R")

# Uvozimo funkcije za pobiranje in uvoz zemljevida.
source("lib/uvozi.zemljevid.r", encoding="UTF-8")
